/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testguidecafinder;

/**
 *
 * @author Drew Kunkel
 */
public class MainPanel extends javax.swing.JFrame {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        decaPanel = new javax.swing.JPanel();
        statsFilterPanel = new javax.swing.JPanel();
        hpCheckBox = new javax.swing.JCheckBox();
        attackCheckBox = new javax.swing.JCheckBox();
        defenseCheckBox = new javax.swing.JCheckBox();
        spdCheckBox = new javax.swing.JCheckBox();
        spaCheckBox = new javax.swing.JCheckBox();
        speedCheckBox = new javax.swing.JCheckBox();
        hpOperation = new javax.swing.JComboBox<>();
        attackOperation = new javax.swing.JComboBox<>();
        defenseOperation = new javax.swing.JComboBox<>();
        spaOperation = new javax.swing.JComboBox<>();
        spdOperation = new javax.swing.JComboBox<>();
        speedOperation = new javax.swing.JComboBox<>();
        hpField = new javax.swing.JFormattedTextField();
        attackField = new javax.swing.JFormattedTextField();
        defenseField = new javax.swing.JFormattedTextField();
        spaField = new javax.swing.JFormattedTextField();
        spdField = new javax.swing.JFormattedTextField();
        speedField = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        generalFilterPanel = new javax.swing.JPanel();
        ability1CheckBox = new javax.swing.JCheckBox();
        ability2CheckBox = new javax.swing.JCheckBox();
        speciesOperation = new javax.swing.JComboBox<>();
        type1Operation = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        speciesCheckbox = new javax.swing.JCheckBox();
        type1CheckBox = new javax.swing.JCheckBox();
        type2CheckBox = new javax.swing.JCheckBox();
        type2Operation = new javax.swing.JComboBox<>();
        ability1Operation = new javax.swing.JComboBox<>();
        ability2Operation = new javax.swing.JComboBox<>();
        type1Field = new javax.swing.JFormattedTextField();
        speciesField = new javax.swing.JFormattedTextField();
        type2Field = new javax.swing.JFormattedTextField();
        ability2Field = new javax.swing.JFormattedTextField();
        ability1Field = new javax.swing.JFormattedTextField();
        textArea1 = new java.awt.TextArea();
        miscFilterPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        friendshipCheckBox = new javax.swing.JCheckBox();
        catchRateCheckBox = new javax.swing.JCheckBox();
        safariRateCheckBox = new javax.swing.JCheckBox();
        expCurveCheckBox = new javax.swing.JCheckBox();
        eggGroup1CheckBox = new javax.swing.JCheckBox();
        eggGroup2CheckBox = new javax.swing.JCheckBox();
        item1CheckBox = new javax.swing.JCheckBox();
        item2CheckBox = new javax.swing.JCheckBox();
        genderCheckBox = new javax.swing.JCheckBox();
        expYieldCheckBox = new javax.swing.JCheckBox();
        dexCheckBox = new javax.swing.JCheckBox();
        curveOperation = new javax.swing.JComboBox<>();
        yieldOperation = new javax.swing.JComboBox<>();
        egg1Operation = new javax.swing.JComboBox<>();
        egg2Operation = new javax.swing.JComboBox<>();
        item1Operation = new javax.swing.JComboBox<>();
        item2Operation = new javax.swing.JComboBox<>();
        friendshipOperation = new javax.swing.JComboBox<>();
        catchRateOperation = new javax.swing.JComboBox<>();
        safariRateOperation = new javax.swing.JComboBox<>();
        genderOperation = new javax.swing.JComboBox<>();
        dexOperation = new javax.swing.JComboBox<>();
        curveField = new javax.swing.JFormattedTextField();
        yieldField = new javax.swing.JFormattedTextField();
        egg1Field = new javax.swing.JFormattedTextField();
        item1Field = new javax.swing.JFormattedTextField();
        item2Field = new javax.swing.JFormattedTextField();
        egg2Field = new javax.swing.JFormattedTextField();
        friendshipField = new javax.swing.JFormattedTextField();
        catchRateField = new javax.swing.JFormattedTextField();
        safariRateField = new javax.swing.JFormattedTextField();
        genderField = new javax.swing.JFormattedTextField();
        dexField = new javax.swing.JFormattedTextField();
        animationcheckBox = new javax.swing.JCheckBox();
        animationOperation = new javax.swing.JComboBox<>();
        animationField = new javax.swing.JFormattedTextField();
        searchButton = new javax.swing.JButton();
        togglePanel = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        statsFilterPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        statsFilterPanel.setName("Stats Filter"); // NOI18N

        hpCheckBox.setText("HP");
        hpCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpCheckBoxActionPerformed(evt);
            }
        });

        attackCheckBox.setText("Attack");
        attackCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackCheckBoxActionPerformed(evt);
            }
        });

        defenseCheckBox.setText("Defense");
        defenseCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defenseCheckBoxActionPerformed(evt);
            }
        });

        spdCheckBox.setText("Sp. Defense");
        spdCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spdCheckBoxActionPerformed(evt);
            }
        });

        spaCheckBox.setText("Sp. Attack");
        spaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spaCheckBoxActionPerformed(evt);
            }
        });

        speedCheckBox.setText("Speed");
        speedCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speedCheckBoxActionPerformed(evt);
            }
        });

        hpOperation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        hpOperation.setToolTipText("Search operation.");

        attackOperation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        attackOperation.setToolTipText("Search operation.");

        defenseOperation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        defenseOperation.setToolTipText("Search operation.");
        defenseOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defenseOperationActionPerformed(evt);
            }
        });

        spaOperation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        spaOperation.setToolTipText("Search operation.");

        spdOperation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        spdOperation.setToolTipText("Search operation.");

        speedOperation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        speedOperation.setToolTipText("Search operation.");

        hpField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hpField.setToolTipText("Between 0 and 255.");

        attackField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        attackField.setToolTipText("Between 0 and 255.");

        defenseField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        defenseField.setToolTipText("Between 0 and 255.");

        spaField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        spaField.setToolTipText("Between 0 and 255.");

        spdField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        spdField.setToolTipText("Between 0 and 255.");

        speedField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        speedField.setToolTipText("Between 0 and 255.");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Operation");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Enable Filter");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Value");

        javax.swing.GroupLayout statsFilterPanelLayout = new javax.swing.GroupLayout(statsFilterPanel);
        statsFilterPanel.setLayout(statsFilterPanelLayout);
        statsFilterPanelLayout.setHorizontalGroup(
            statsFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsFilterPanelLayout.createSequentialGroup()
                .addGroup(statsFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statsFilterPanelLayout.createSequentialGroup()
                        .addGroup(statsFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, statsFilterPanelLayout.createSequentialGroup()
                                .addGroup(statsFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hpCheckBox)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(statsFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(hpOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, statsFilterPanelLayout.createSequentialGroup()
                                .addGroup(statsFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, statsFilterPanelLayout.createSequentialGroup()
                                        .addComponent(spdCheckBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(spdOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, statsFilterPanelLayout.createSequentialGroup()
                                        .addComponent(spaCheckBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(spaOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, statsFilterPanelLayout.createSequentialGroup()
                                        .addComponent(defenseCheckBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(defenseOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(17, 17, 17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addComponent(attackCheckBox)
                    .addGroup(statsFilterPanelLayout.createSequentialGroup()
                        .addGroup(statsFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(statsFilterPanelLayout.createSequentialGroup()
                                .addComponent(speedCheckBox)
                                .addGap(58, 58, 58)
                                .addComponent(speedOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(attackOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(statsFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hpField, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(attackField)
                            .addComponent(defenseField)
                            .addComponent(spaField)
                            .addComponent(spdField)
                            .addComponent(speedField))))
                .addGap(34, 34, 34))
        );
        statsFilterPanelLayout.setVerticalGroup(
            statsFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsFilterPanelLayout.createSequentialGroup()
                .addGroup(statsFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statsFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hpCheckBox)
                    .addComponent(hpOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attackCheckBox)
                    .addComponent(attackOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attackField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(defenseCheckBox)
                    .addComponent(defenseOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(defenseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spaCheckBox)
                    .addComponent(spaOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spdCheckBox)
                    .addComponent(spdOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speedCheckBox)
                    .addComponent(speedOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(143, 143, 143))
        );

        generalFilterPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ability1CheckBox.setText("Ability 1");
        ability1CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ability1CheckBoxActionPerformed(evt);
            }
        });

        ability2CheckBox.setText("Ability 2");
        ability2CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ability2CheckBoxActionPerformed(evt);
            }
        });

        speciesOperation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        speciesOperation.setToolTipText("Search operation.");

        type1Operation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        type1Operation.setToolTipText("Search operation.");
        type1Operation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type1OperationActionPerformed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Enable Filter");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Operation");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Value");

        speciesCheckbox.setText("Species");
        speciesCheckbox.setToolTipText("Species index number. Every species past index 411 are glitch Pokemon and use extrapolated data. Additionally, species 0 is a blank space, and species 252-276 are placeholder ?? Pokemon.");

        type1CheckBox.setText("Type 1");

        type2CheckBox.setText("Type 2");
        type2CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type2CheckBoxActionPerformed(evt);
            }
        });

        type2Operation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        type2Operation.setToolTipText("Search operation.");

        ability1Operation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        ability1Operation.setToolTipText("Search operation.");

        ability2Operation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        ability2Operation.setToolTipText("Search operation.");

        type1Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        type1Field.setToolTipText("Between 0 and 255.");

        speciesField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        speciesField.setToolTipText("Between 0 and 65535.");

        type2Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        type2Field.setToolTipText("Between 0 and 255.");

        ability2Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ability2Field.setToolTipText("Between 0 and 255.");

        ability1Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ability1Field.setToolTipText("Between 0 and 255.");

        javax.swing.GroupLayout generalFilterPanelLayout = new javax.swing.GroupLayout(generalFilterPanel);
        generalFilterPanel.setLayout(generalFilterPanelLayout);
        generalFilterPanelLayout.setHorizontalGroup(
            generalFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalFilterPanelLayout.createSequentialGroup()
                        .addGroup(generalFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ability1CheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(generalFilterPanelLayout.createSequentialGroup()
                                .addComponent(ability2CheckBox)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(125, 125, 125))
                    .addGroup(generalFilterPanelLayout.createSequentialGroup()
                        .addGroup(generalFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(type2CheckBox)
                            .addComponent(type1CheckBox)
                            .addComponent(speciesCheckbox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(generalFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(generalFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generalFilterPanelLayout.createSequentialGroup()
                                    .addComponent(type1Operation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(type1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generalFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, generalFilterPanelLayout.createSequentialGroup()
                                        .addGroup(generalFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ability1Operation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(type2Operation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ability2Operation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(generalFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ability2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ability1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(type2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(generalFilterPanelLayout.createSequentialGroup()
                                        .addComponent(speciesOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(speciesField))))
                            .addGroup(generalFilterPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(23, 23, 23))))
        );
        generalFilterPanelLayout.setVerticalGroup(
            generalFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalFilterPanelLayout.createSequentialGroup()
                .addGroup(generalFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speciesCheckbox)
                    .addComponent(speciesOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speciesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type1CheckBox)
                    .addComponent(type1Operation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type2CheckBox)
                    .addComponent(type2Operation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ability1CheckBox)
                    .addComponent(ability1Operation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ability1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ability2CheckBox)
                    .addComponent(ability2Operation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ability2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textArea1.setEditable(false);

        miscFilterPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Enable Filter");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Operation");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Value");

        friendshipCheckBox.setText("Friendship");
        friendshipCheckBox.setToolTipText("Base friendship when caught.");

        catchRateCheckBox.setText("Catch Rate");
        catchRateCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catchRateCheckBoxActionPerformed(evt);
            }
        });

        safariRateCheckBox.setText("Safari Rate");
        safariRateCheckBox.setToolTipText("Determines flee rate if encountered in the Safari Zone.");
        safariRateCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                safariRateCheckBoxActionPerformed(evt);
            }
        });

        expCurveCheckBox.setText("EXP Curve");
        expCurveCheckBox.setToolTipText("Experience curve that determines how much experience a pokemon needs to level up.\n0 : Medium Fast\n1 : Erratic\n2 : Fluctuating\n3 : Medium Slow\n4 : Fast\n5 : Slow\n6 : Medium Fast (Copy)\n7 : Medium Fast (Copy)\n8+ : Glitch\n");

        eggGroup1CheckBox.setText("Egg Group 1");
        eggGroup1CheckBox.setToolTipText("Determines what pokemon this species can be bred with.\n1  : Monster\n2  : Water 1\n3  : Bug\n4  : Flying\n5  : Field\n6  : Fairy\n7  : Grass\n8  : Human-Like\n9  : Water 3\n10: Mineral\n11: Amorphous\n12: Water 2\n13: Ditto\n14: Dragon\n15: Undiscovered\n16+ : Glitch");

        eggGroup2CheckBox.setText("Egg Group 2");
        eggGroup2CheckBox.setToolTipText("Determines what pokemon this species can be bred with.\n1  : Monster\n2  : Water 1\n3  : Bug\n4  : Flying\n5  : Field\n6  : Fairy\n7  : Grass\n8  : Human-Like\n9  : Water 3\n10: Mineral\n11: Amorphous\n12: Water 2\n13: Ditto\n14: Dragon\n15: Undiscovered\n16+: Glitch");

        item1CheckBox.setText("Item 1");
        item1CheckBox.setToolTipText("If an item is assigned to Item 1, the Pokémon will have a 50% chance of having that item when encountered in the wild. An item assigned to Item 2 will have a 5% chance of being held. If both Item 1 and Item 2 are the same, then the Pokémon will always be holding that item when it is encountered.");

        item2CheckBox.setText("Item 2");
        item2CheckBox.setToolTipText("If an item is assigned to Item 1, the Pokémon will have a 50% chance of having that item when encountered in the wild. An item assigned to Item 2 will have a 5% chance of being held. If both Item 1 and Item 2 are the same, then the Pokémon will always be holding that item when it is encountered.");

        genderCheckBox.setText("Gender");
        genderCheckBox.setToolTipText("0        : Always male.\n1-253 : Mixed\n254    : Always female.\n255    : No gender.");

        expYieldCheckBox.setText("EXP Yield");
        expYieldCheckBox.setToolTipText("Base EXP yield used to calculate experience from defeating this pokemon.");
        expYieldCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expYieldCheckBoxActionPerformed(evt);
            }
        });

        dexCheckBox.setText("Dex Number");
        dexCheckBox.setToolTipText("Pokedex number (seperate from species number).");
        dexCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dexCheckBoxActionPerformed(evt);
            }
        });

        curveOperation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        curveOperation.setToolTipText("Search operation.");

        yieldOperation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        yieldOperation.setToolTipText("Search operation.");
        yieldOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yieldOperationActionPerformed(evt);
            }
        });

        egg1Operation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        egg1Operation.setToolTipText("Search operation.");

        egg2Operation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        egg2Operation.setToolTipText("Search operation.");

        item1Operation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        item1Operation.setToolTipText("Search operation.");

        item2Operation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        item2Operation.setToolTipText("Search operation.");

        friendshipOperation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        friendshipOperation.setToolTipText("Search operation.");

        catchRateOperation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        catchRateOperation.setToolTipText("Search operation.");
        catchRateOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catchRateOperationActionPerformed(evt);
            }
        });

        safariRateOperation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        safariRateOperation.setToolTipText("Search operation.");
        safariRateOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                safariRateOperationActionPerformed(evt);
            }
        });

        genderOperation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        genderOperation.setToolTipText("Search operation.");

        dexOperation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        dexOperation.setToolTipText("Search operation.");
        dexOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dexOperationActionPerformed(evt);
            }
        });

        curveField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        curveField.setToolTipText("Between 0 and 255.");

        yieldField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        yieldField.setToolTipText("Between 0 and 255.");

        egg1Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        egg1Field.setToolTipText("Between 0 and 255.");

        item1Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        item1Field.setToolTipText("Between 0 and 65535.");

        item2Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        item2Field.setToolTipText("Between 0 and 65535.");

        egg2Field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        egg2Field.setToolTipText("Between 0 and 255.");

        friendshipField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        friendshipField.setToolTipText("Between 0 and 255.");

        catchRateField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        catchRateField.setToolTipText("Between 0 and 255.");

        safariRateField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        safariRateField.setToolTipText("Between 0 and 255.");

        genderField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        genderField.setToolTipText("Between 0 and 255.");

        dexField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        dexField.setToolTipText("Between 0 and 65535.");

        animationcheckBox.setText("Animation ID");

        animationOperation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", ">", "<" }));
        animationOperation.setToolTipText("Search operation.");

        animationField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        animationField.setToolTipText("Between 0 and 255.");

        javax.swing.GroupLayout miscFilterPanelLayout = new javax.swing.GroupLayout(miscFilterPanel);
        miscFilterPanel.setLayout(miscFilterPanelLayout);
        miscFilterPanelLayout.setHorizontalGroup(
            miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miscFilterPanelLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(miscFilterPanelLayout.createSequentialGroup()
                .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(miscFilterPanelLayout.createSequentialGroup()
                        .addComponent(safariRateCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(safariRateOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(miscFilterPanelLayout.createSequentialGroup()
                        .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderCheckBox)
                            .addComponent(dexCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderOperation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dexOperation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(miscFilterPanelLayout.createSequentialGroup()
                        .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eggGroup2CheckBox)
                            .addComponent(item1CheckBox)
                            .addComponent(item2CheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(item2Operation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(item1Operation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(egg2Operation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(miscFilterPanelLayout.createSequentialGroup()
                        .addComponent(eggGroup1CheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(egg1Operation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(miscFilterPanelLayout.createSequentialGroup()
                        .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(expCurveCheckBox)
                            .addComponent(expYieldCheckBox))
                        .addGap(35, 35, 35)
                        .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(yieldOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(curveOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, miscFilterPanelLayout.createSequentialGroup()
                        .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(friendshipCheckBox)
                            .addComponent(catchRateCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(catchRateOperation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(friendshipOperation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(curveField)
                    .addComponent(yieldField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(egg1Field, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(item1Field, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(item2Field, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(egg2Field, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(friendshipField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(catchRateField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(safariRateField)
                    .addComponent(genderField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dexField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(miscFilterPanelLayout.createSequentialGroup()
                .addComponent(animationcheckBox)
                .addGap(19, 19, 19)
                .addComponent(animationOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(animationField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        miscFilterPanelLayout.setVerticalGroup(
            miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miscFilterPanelLayout.createSequentialGroup()
                .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expCurveCheckBox)
                    .addComponent(curveOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(curveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expYieldCheckBox)
                    .addComponent(yieldOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yieldField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eggGroup1CheckBox)
                    .addComponent(egg1Operation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(egg1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(egg2Operation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eggGroup2CheckBox)
                        .addComponent(egg2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item1CheckBox)
                    .addComponent(item1Operation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item2CheckBox)
                    .addComponent(item2Operation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(friendshipCheckBox)
                    .addComponent(friendshipOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(friendshipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catchRateCheckBox)
                    .addComponent(catchRateOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catchRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(safariRateCheckBox)
                    .addComponent(safariRateOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(safariRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderCheckBox)
                    .addComponent(genderOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dexCheckBox)
                    .addComponent(dexOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(miscFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(animationcheckBox)
                    .addComponent(animationOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(animationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        togglePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jRadioButton1.setText("Display learnset.");
        jRadioButton1.setToolTipText("Pokemon with a learnset size above 255 cannot level up.");

        jRadioButton2.setText("Display evolutions.");
        jRadioButton2.setToolTipText("Set to filter Pokemon that can evolve into normal Pokemon.");

        jRadioButton3.setText("Display name in byte form.");
        jRadioButton3.setToolTipText("Set to filter Pokemon that can evolve into other glitch Pokemon.");

        jRadioButton4.setText("Show ability name.");
        jRadioButton4.setToolTipText("To be implemented later.");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setText("Perfect EV Yield.");

        javax.swing.GroupLayout togglePanelLayout = new javax.swing.GroupLayout(togglePanel);
        togglePanel.setLayout(togglePanelLayout);
        togglePanelLayout.setHorizontalGroup(
            togglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(togglePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(togglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3)
                    .addGroup(togglePanelLayout.createSequentialGroup()
                        .addGroup(togglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addGap(18, 18, 18)
                        .addGroup(togglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        togglePanelLayout.setVerticalGroup(
            togglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(togglePanelLayout.createSequentialGroup()
                .addGroup(togglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(togglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton3)
                .addContainerGap())
        );

        javax.swing.GroupLayout decaPanelLayout = new javax.swing.GroupLayout(decaPanel);
        decaPanel.setLayout(decaPanelLayout);
        decaPanelLayout.setHorizontalGroup(
            decaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(decaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(generalFilterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statsFilterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(miscFilterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(decaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(decaPanelLayout.createSequentialGroup()
                        .addComponent(togglePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        decaPanelLayout.setVerticalGroup(
            decaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(decaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(decaPanelLayout.createSequentialGroup()
                        .addGroup(decaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(miscFilterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(decaPanelLayout.createSequentialGroup()
                                .addComponent(generalFilterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statsFilterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(decaPanelLayout.createSequentialGroup()
                        .addGroup(decaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(togglePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jTabbedPane2.addTab("Decamark Finder", decaPanel);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 992, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Move Finder", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 992, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Advanced Searches", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hpCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hpCheckBoxActionPerformed

    private void attackCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attackCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attackCheckBoxActionPerformed

    private void defenseCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defenseCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_defenseCheckBoxActionPerformed

    private void spdCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spdCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spdCheckBoxActionPerformed

    private void spaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spaCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spaCheckBoxActionPerformed

    private void speedCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speedCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_speedCheckBoxActionPerformed

    private void ability1CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ability1CheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ability1CheckBoxActionPerformed

    private void defenseOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defenseOperationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_defenseOperationActionPerformed

    private void safariRateCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_safariRateCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_safariRateCheckBoxActionPerformed

    private void ability2CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ability2CheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ability2CheckBoxActionPerformed

    private void type2CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type2CheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_type2CheckBoxActionPerformed

    private void catchRateCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catchRateCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catchRateCheckBoxActionPerformed

    private void expYieldCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expYieldCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expYieldCheckBoxActionPerformed

    private void dexCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dexCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dexCheckBoxActionPerformed

    private void yieldOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yieldOperationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yieldOperationActionPerformed

    private void catchRateOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catchRateOperationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catchRateOperationActionPerformed

    private void safariRateOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_safariRateOperationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_safariRateOperationActionPerformed

    private void dexOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dexOperationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dexOperationActionPerformed

    private void type1OperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type1OperationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_type1OperationActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        System.out.println("test");
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ability1CheckBox;
    private javax.swing.JFormattedTextField ability1Field;
    private javax.swing.JComboBox<String> ability1Operation;
    private javax.swing.JCheckBox ability2CheckBox;
    private javax.swing.JFormattedTextField ability2Field;
    private javax.swing.JComboBox<String> ability2Operation;
    private javax.swing.JFormattedTextField animationField;
    private javax.swing.JComboBox<String> animationOperation;
    private javax.swing.JCheckBox animationcheckBox;
    private javax.swing.JCheckBox attackCheckBox;
    private javax.swing.JFormattedTextField attackField;
    private javax.swing.JComboBox<String> attackOperation;
    private javax.swing.JCheckBox catchRateCheckBox;
    private javax.swing.JFormattedTextField catchRateField;
    private javax.swing.JComboBox<String> catchRateOperation;
    private javax.swing.JFormattedTextField curveField;
    private javax.swing.JComboBox<String> curveOperation;
    private javax.swing.JPanel decaPanel;
    private javax.swing.JCheckBox defenseCheckBox;
    private javax.swing.JFormattedTextField defenseField;
    private javax.swing.JComboBox<String> defenseOperation;
    private javax.swing.JCheckBox dexCheckBox;
    private javax.swing.JFormattedTextField dexField;
    private javax.swing.JComboBox<String> dexOperation;
    private javax.swing.JFormattedTextField egg1Field;
    private javax.swing.JComboBox<String> egg1Operation;
    private javax.swing.JFormattedTextField egg2Field;
    private javax.swing.JComboBox<String> egg2Operation;
    private javax.swing.JCheckBox eggGroup1CheckBox;
    private javax.swing.JCheckBox eggGroup2CheckBox;
    private javax.swing.JCheckBox expCurveCheckBox;
    private javax.swing.JCheckBox expYieldCheckBox;
    private javax.swing.JCheckBox friendshipCheckBox;
    private javax.swing.JFormattedTextField friendshipField;
    private javax.swing.JComboBox<String> friendshipOperation;
    private javax.swing.JCheckBox genderCheckBox;
    private javax.swing.JFormattedTextField genderField;
    private javax.swing.JComboBox<String> genderOperation;
    private javax.swing.JPanel generalFilterPanel;
    private javax.swing.JCheckBox hpCheckBox;
    private javax.swing.JFormattedTextField hpField;
    private javax.swing.JComboBox<String> hpOperation;
    private javax.swing.JCheckBox item1CheckBox;
    private javax.swing.JFormattedTextField item1Field;
    private javax.swing.JComboBox<String> item1Operation;
    private javax.swing.JCheckBox item2CheckBox;
    private javax.swing.JFormattedTextField item2Field;
    private javax.swing.JComboBox<String> item2Operation;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel miscFilterPanel;
    private javax.swing.JCheckBox safariRateCheckBox;
    private javax.swing.JFormattedTextField safariRateField;
    private javax.swing.JComboBox<String> safariRateOperation;
    private javax.swing.JButton searchButton;
    private javax.swing.JCheckBox spaCheckBox;
    private javax.swing.JFormattedTextField spaField;
    private javax.swing.JComboBox<String> spaOperation;
    private javax.swing.JCheckBox spdCheckBox;
    private javax.swing.JFormattedTextField spdField;
    private javax.swing.JComboBox<String> spdOperation;
    private javax.swing.JCheckBox speciesCheckbox;
    private javax.swing.JFormattedTextField speciesField;
    private javax.swing.JComboBox<String> speciesOperation;
    private javax.swing.JCheckBox speedCheckBox;
    private javax.swing.JFormattedTextField speedField;
    private javax.swing.JComboBox<String> speedOperation;
    private javax.swing.JPanel statsFilterPanel;
    private java.awt.TextArea textArea1;
    private javax.swing.JPanel togglePanel;
    private javax.swing.JCheckBox type1CheckBox;
    private javax.swing.JFormattedTextField type1Field;
    private javax.swing.JComboBox<String> type1Operation;
    private javax.swing.JCheckBox type2CheckBox;
    private javax.swing.JFormattedTextField type2Field;
    private javax.swing.JComboBox<String> type2Operation;
    private javax.swing.JFormattedTextField yieldField;
    private javax.swing.JComboBox<String> yieldOperation;
    // End of variables declaration//GEN-END:variables
}
